apiVersion: v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: docker.io/cgcodefresh/springboot:master
        ports:
        - containerPort: 80
